CREATE TABLE PROBLEMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SLUG VARCHAR(255) NOT NULL UNIQUE,
    TITLE VARCHAR(255) NOT NULL,
    DIFFICULTY VARCHAR(50) NOT NULL,
    DESCRIPTION LONGTEXT NOT NULL,
    CONSTRAINTS TEXT,
    STATUS VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);